### ISSUE TITLE
Starting the project errors

### ISSUE THREAD

**Issue by DZKeeper** [SpamScope/spamscope-docker-compose#1]
Hi,

Seems there is a lot of potential here, thats why I want to try spamscope. However, after struggling trying to wrap my head around the documentation I decided to try using the docker compose concept, I somewhat got things going but i am facing errors:

1) If I modify .env file and leave the double quotes around my paths in these three configs variable:

> DOCKER_MAILS_FOLDER="/path/in/docker/container"
> ...
> HOST_MAILS_FOLDER="/path/in/host"
> HOST_SPAMSCOPE_CONF="/path/conf/in/host"

I get the following error:

> ERROR: Named volume ""/etc/spamscope/conf":/etc/spamscope:rw" is used in service "spamscope" but no declaration was found in the volumes section

2) After removing all the double quotes in the .env file, and running : "sudo docker-compose up -d" it seems to have installed everything but I get this error:

> Starting elasticsearch ... 
> Starting elasticsearch ... done
> kibana is up-to-date
> 
> ERROR: for spamscope  Container "bc954bc8fc07" is unhealthy.
> ERROR: Encountered errors while bringing up the project.

This ID (bc954bc8fc07) corresponds to the elasticsearch docker container.

Any help is appreciated,
Thanks in advance

**Comment by DZKeeper** [comment]
Follow UP: I got things going by doing this in my Ubuntu VM: "sudo sysctl -w vm.max_map_count=262144"

and increasing ram of the VM.

How do I test the processing ?
Whats the default index I should tell Kibana to look for ?

**Comment by fedelemantuano** [comment]
It's not a SpamScope issue, but Elasticsearch needs this setting (https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode).
I will put this in README.

If you know Docker, it's easy to install SpamScope. The docker images are good examples, if you want to customize a your own image start from [spamscope-root](https://hub.docker.com/r/fmantuano/spamscope-root/).

If you want test, you should see configuration file example [here](https://github.com/SpamScope/spamscope/blob/develop/conf/spamscope.example.yml). There are a lot of comments.

[Here](https://github.com/SpamScope/spamscope/blob/develop/conf/spamscope.example.yml#L247) Elasticsearch configuration with the index name that you can change.

_However, after struggling trying to wrap my head around the documentation_
What are your main problems?

**Comment by DZKeeper** [comment]
Thank you for the answers.

> What are your main problems?

While some of these tech are new to me, I guess the various installation options made it confusing to me, and the level of details for each method will vary. I guess I was looking for a spoonfeeding tutorial to get me started...

Like right now, I got my three dockers running, I have copied a sample text email in my host folder, how do I know if it has been ingested ? or in the process of being analysed ?

I think I am missing some configs, mainly the keywords config file mentioned [here](https://github.com/SpamScope/spamscope/tree/develop/conf/keywords), are they mandatory when using docker ?

**Comment by fedelemantuano** [comment]
Before you have to read [main SpamScope README](https://github.com/SpamScope/spamscope/blob/develop/README.md) and you should see the [main configuration file example](https://github.com/SpamScope/spamscope/blob/develop/conf/spamscope.example.yml).

SpamScope runs on [Apache Storm](http://storm.apache.org/), so you have to start Apache Storm and then you have to submit SpamScope topology as I wrote [here](https://github.com/SpamScope/spamscope-docker-compose#usage).
The official SpamScope images have Apache Storm running and three SpamScope topologies that you can use.

Before all you have to configure SpamScope and then submit the topology. In this case, if you configured SpamScope, you have to use ony 2 (two) commands:

```
$ sudo docker-compose up -d
$ sudo docker-compose exec spamscope spamscope-topology submit -g spamscope_elasticsearch 
```
If in the folder, that you configured, there are mails, you will see those mails in Elasticsearch.

In my guide I suppose that you know `Docker`, `docker-compose`, a little bit `Apache Storm` and `ELK` stack.
